# Generated by Django 3.1.7 on 2021-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210411_1136'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', unique=True),
        ),
    ]
