# Generated by Django 3.1.7 on 2021-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0004_auto_20210416_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='note',
            field=models.CharField(default='', max_length=50),
        ),
    ]
