# Generated by Django 3.1.7 on 2021-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0005_medicine_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='duration',
            field=models.CharField(default='', max_length=10),
        ),
    ]
