# Generated by Django 3.1.7 on 2021-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='consult_mode',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
