# Generated by Django 3.1.7 on 2021-04-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20210411_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.apttoken', unique=True),
        ),
    ]
