# Generated by Django 3.1.7 on 2021-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210411_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='apttoken',
            name='slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
