# Generated by Django 3.1.7 on 2021-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_apttoken_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apttoken',
            name='slot',
            field=models.CharField(default='', max_length=10),
        ),
    ]
