# Generated by Django 3.1.7 on 2021-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210422_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='apttoken',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
