# Generated by Django 3.1.7 on 2021-04-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210405_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
    ]
