# Generated by Django 3.1.7 on 2021-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_auto_20210416_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='total_quantity',
            field=models.CharField(default='', max_length=10),
        ),
    ]
