# Generated by Django 3.1.7 on 2021-04-10 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_doctordetail_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AptToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('date_expected', models.DateField()),
                ('time_posted', models.DateTimeField(auto_now=True)),
                ('doctor_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctordetail')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=52)),
                ('consult_mode', models.CharField(max_length=20)),
                ('datetime_allocated', models.DateTimeField()),
                ('time_posted', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.apttoken')),
            ],
        ),
    ]
